# Write a python script to realize 3 inputs bipolar NOR gate using perceptron
The following code trains a percepton neural metwork model to realize 3-inputs bipolar NOR gate. The perceptron model has a bias input = 1 and a random bias weight. The value of the learning rate and theta can be given at runtime. The code uses the Numpy package extensively for matrix computations. The accuracy (0% or 100%) of the model on testing data is also calculated and displayed .

In [1]:
# import necessary libraries
import numpy as np

In [2]:
# Function to train the perceptron model to realise  NOR gate
def learn(inputs, target, weight, theta, lr=0.01):
    yout = np.zeros(8, dtype=int)
    yin = 0
    epoch = 1
    print("\n========== THE LEARNING PHASE ==========\n")
    while True:
        print("========= EPOCH ",epoch,"=========")     
        for i in range(8):          
            x = inputs[i] # takes each training set one by one
            yin = 0  # reset yin
            # Calculate net input
            yin = np.dot(x.T, weight)
            yin = yin.item()    # Get Python datatype value from scalar Numpy array
            # Calculate output
            if yin > theta:
                #print("************ Greater")
                np.put(yout,i,1)
            elif yin < (-theta):
                #print("************ Lesser")
                np.put(yout,i,-1)
            else:
                #print("************ Middle")
                np.put(yout,i,0)
            #print("net output -         ",yout[i])
            # Check for error
            if yout[i] != target[i]:
                for j in range(4):
                    weight[j] += lr*target[i]*x[j]  # update weights if error exists
        epoch += 1
        # Display the weights and outputs generated in this epoch
        print("Weights : ")
        print(np.array2string(np.float_(([ '%.3f' % elem for elem in weight ])), separator=', '))
        print("Outputs : ")
        print(yout)
        if np.array_equal(target,yout):
            break  # Terminate loop if every output matches with correspondingtarget
    print("\n=============================\nThe Target was : ")
    print(target)
    print("The Final Outputs are : ")
    print(yout)
    print("The Final Weights are : ")
    print(np.array2string(np.float_(([ '%.3f' % elem for elem in weight ])), separator=', '))
    print("\n=============================\n")
    return weight

In [3]:
# Function to calculate the accuracy of the model
def get_accuracy(test_inp, test_out, true_inp, true_out):
    index = -1
    for i in range(8):
        if((true_inp[i] == test_inp).all()):
            index = i
            break
        #index = np.where((true_inp[i] == test_inp).all())
    accuracy = test_out == true_out[index]
    return accuracy

In [4]:
# Initialise the perceptron model
weights = np.random.randn(4)  # weights along with bias weight
bias = 1  # bias input
l = float(input("Enter the learning rate >> "))  # learning rate of the perceptron
theta = float(input("Enter the value of theta >> "))  # theta value of the perceptron
print("Initial Weights : ",weights)

Enter the learning rate >> 1
Enter the value of theta >> 1
Initial Weights :  [ 0.12373354  0.49783323 -0.90658615 -1.01653372]


In [5]:
# 3 bit binary data for 3 i/p NOR gate
inp = np.array([ 
    [-1, -1, -1], 
    [-1, -1, 1], 
    [-1, 1, -1], 
    [-1, 1, 1], 
    [1, -1, -1], 
    [1, -1, 1], 
    [1, 1, -1], 
    [1, 1, 1] 
])
target = np.array(
    [1, -1, -1, -1, -1, -1, -1, -1]
)

In [6]:
# Append bias input
inp = np.insert(inp,0,1,axis = 1)

In [7]:
#weights = np.zeros(4)
weights = learn(inp, target, weights, theta, l)  # Train the model


========== THE LEARNING PHASE ==========

========= EPOCH  1 =========
Weights : 
[-2.876,  1.498,  0.093, -0.017]
Outputs : 
[ 1  0  0 -1  1 -1 -1 -1]
========= EPOCH  2 =========
Weights : 
[-2.876, -0.502,  0.093, -0.017]
Outputs : 
[-1 -1 -1 -1  0 -1 -1 -1]
========= EPOCH  3 =========
Weights : 
[-3.876,  0.498, -0.907, -1.017]
Outputs : 
[-1  0  0 -1 -1 -1 -1 -1]
========= EPOCH  4 =========
Weights : 
[-3.876, -1.502, -0.907, -1.017]
Outputs : 
[-1 -1 -1 -1  0 -1 -1 -1]
========= EPOCH  5 =========
Weights : 
[-4.876, -0.502, -1.907, -2.017]
Outputs : 
[ 0  0  0 -1 -1 -1 -1 -1]
========= EPOCH  6 =========
Weights : 
[-4.876, -2.502, -1.907, -2.017]
Outputs : 
[ 0 -1 -1 -1  0 -1 -1 -1]
========= EPOCH  7 =========
Weights : 
[-4.876, -2.502, -1.907, -2.017]
Outputs : 
[ 1 -1 -1 -1 -1 -1 -1 -1]

The Target was : 
[ 1 -1 -1 -1 -1 -1 -1 -1]
The Final Outputs are : 
[ 1 -1 -1 -1 -1 -1 -1 -1]
The Final Weights are : 
[-4.876, -2.502, -1.907, -2.017]




In [10]:
print("\n========== THE TESTING PHASE ==========\n")
# Initialise test input
n = np.ones(4)
for i in range(1,4):
    np.put(n,i,int(input("ENTER THE INPUT >> ")))
# Calculate net input
y_in = np.sum(np.dot(n.T, weights))
#print(yin)
y_in = y_in.item()  # Get Python datatype value from scalar Numpy array
# Calculate output
if y_in > theta:
    yout = 1
elif y_in < (-theta):
    yout = -1
else:
    yout = 0
    
# Display results
n = n.astype('int32')
print("Input : \n",n[1:])
print("Output : ",yout)

accuracy = get_accuracy(n,yout, inp, target) * 100
print("Accuracy of model : %3.2f"%accuracy+"%")


========== THE TESTING PHASE ==========

ENTER THE INPUT >> -1
ENTER THE INPUT >> 1
ENTER THE INPUT >> 1
Input : 
 [-1  1  1]
Output :  -1
Accuracy of model : 100.00%
